### ISSUE TITLE
Double "tab" to trigger snippets

### ISSUE THREAD

**Issue by gusaiani** [msaraiva/atom-elixir#1]
Hi @msaraiva,

I’ve been using the package, and notice that it’s necessary to hit tab twice every time a user needs to trigger a snippet.

By disabling the package, the behavior reverts to normal: 1 tab keydown to trigger the snippet.

All the best!
Gustavo

**Comment by msaraiva** [comment]
@gusaiani It's fixed!. Try to `git pull` the package and restart Atom. Let me know if it's working. Thanks for the feedback!

**Comment by gusaiani** [comment]
Yup, it’s working. :100:
