### ISSUE TITLE
module Support.Helpers is not loaded and could not be found

### ISSUE THREAD

**Issue by mgwidmann** [msaraiva/atom-elixir#15]
Awesome package! Can't wait for this to be ready.

Just installed the package and when I do ctrl + shift + x I see this:

![image](https://cloud.githubusercontent.com/assets/5035724/13440549/88469b86-dfc0-11e5-9e92-79652453b6b3.png)

**Comment by mgwidmann** [comment]
So I figured out that this does work when I place it in other files. This example was placed into a test file, which in phoenix uses `def elixirc_paths(:test), do: ["lib", "test"]` to add it to the compile path. When I try to expand anything inside a file that uses the compiled test code it complains that the module doesn't exist.

**Comment by msaraiva** [comment]
@mgwidmann thanks for the feedback. I'll take a look at it.

**Comment by mgwidmann** [comment]
Thanks, I suspect because the module only exists in the test env and so it fails. Not sure what you should do about it...

Thanks a bunch for this plugin though, its really awesome!

**Comment by msaraiva** [comment]
Fixed!
