### ISSUE TITLE
Autocompletion for package from dependencies.

### ISSUE THREAD

**Issue by eddwardo** [msaraiva/atom-elixir#22]
I am having a problem with autocompletion for packages from my dependencies.
1. mix new some_app
2. add `ecto` to mix dependencies
3. mix deps.get, deps.compile
4. open some_app.ex in lib directory, type Ecto. - nothing happens.

Am I missing something here ?

**Comment by msaraiva** [comment]
Can you confirm you have the *.beam files in your `./_build/dev/lib/ecto/ebin/`? In case you don't, then something went wrong while compiling the project. Autocomplete needs the compiled beam files to work properly. In case you DO have those files, please send more information (OS, Elixir version, Atom version, installed packages, etc.) so I can investigate the issue.

Thanks.

**Comment by eddwardo** [comment]
There are some `*.beam` files in 
```
ls _build/dev/lib/ecto/ebin/*beam | wc -l
     115
```

Atom version: 1.5.4
Atom Package version: atom-elixir@0.1.4
Elixir: 1.2.2


I also noticed that my linter doesn't discover Ecto, so It might be something with my setup.

https://www.dropbox.com/s/7e15n3wn908853v/Screenshot%202016-03-15%2011.36.05.png?dl=0

**Comment by msaraiva** [comment]
@eddwardo try to open your atom console (`option+cmd+i` on OSX). There should be log messages out there that might help us to find out what's going on.

**Comment by eddwardo** [comment]
@msaraiva All I see is:
https://www.dropbox.com/s/ytmqjbfrivdvqb1/Screenshot%202016-03-16%2011.42.02.png?dl=0

**Comment by eddwardo** [comment]
Calling `mix test` solved the issue.
