### ISSUE TITLE
Installing Atom package does not work

### ISSUE THREAD

**Issue by kraades** [msaraiva/atom-elixir#24]
Installing the Atom package takes forever and does not work. If you try to uninstall you get error message below.

On Ubuntu 15.10 64-bit, Windows 8.1 64-bit and Windows 2012 R2 64-bit and the latest Atom version.

Edit:
I installed from the GUI. If I install using the command line it works but I had to disable/enable the package first. Not sure what went wrong.

![atom-elixir](https://cloud.githubusercontent.com/assets/1192076/14582297/2974210e-0401-11e6-8554-f5efc110f31c.PNG)

**Comment by msaraiva** [comment]
@kraades thanks for the feedback. It's going to be really hard for me to find out what went wrong. I can't reproduce the problem on any of my testing environments. Does it always happen when you try to uninstall and install again?
