### ISSUE TITLE
Autocompletion isn't work

### ISSUE THREAD

**Issue by insiderq** [msaraiva/atom-elixir#25]
I've installer a plugin, i've seen in console "Initializing alchemist-server for environment "dev" (Elixir version 1.1.1)", F2 works, but autocompletion isn't what am i doing wrong?

**Comment by insiderq** [comment]
The plugin autocomplete-plus was disabled, that wasn't clear

**Comment by msaraiva** [comment]
@insiderq Thanks for the feedback!
