### ISSUE TITLE
Documentation don't work properly

### ISSUE THREAD

**Issue by Hostert** [msaraiva/atom-elixir#28]
Hello.

I'm trying to use documentation for every function, but just some works.
For example: When I call `F2`on `def`, works ok with this console output:

`[Server] DOCL { "def", "/tmp/vyjxlfpd8", 10 } server-process.coffee:149`

When I call on `String.duplicate`, nothing happens and console logs this:

`[atom-elixir] %FunctionClauseError{arity: 2, function: :do_lookup_docs, module: Code} server-process.coffee:55`

In time, I would like to ask if you can use `F2` key to open docs and after called a second time, close the panel.

**Comment by VladShcherbin** [comment]
Same issue.

**Comment by msaraiva** [comment]
There's a new version v0.2.1. Please, update and check if the problem is gone. Also remember to restart Atom after update or hit `CTRL+ALT-CMD-L` on mac.

Thanks for reporting the issue.
