### ISSUE TITLE
Breaks descriptions of other autocomplete packages

### ISSUE THREAD

**Issue by ScrimpyCat** [msaraiva/atom-elixir#31]
When using this package, other autocomplete packages stop working correctly. Their descriptions no longer show up. My current solution is to disable this package everytime I'm working on non-elixir code, and then re-enable it when I'm working on elixir code. 

The culprit as far as I can tell is https://github.com/msaraiva/atom-elixir/blob/master/lib/elixir-autocomplete-provider.coffee#L25 Because it's changing the default description view, which is then affecting all packages. I'm not familiar with how autocomplete-plus is managing its views across editors, but is there any reasonable way we could have this custom description view only apply to editors currently using the `.source.elixir` grammar.

**Comment by msaraiva** [comment]
@ScrimpyCat this is already fixed on master and will be in version 0.2.0 (to be released hopefully tomorrow)
Thanks for the feedback!

**Comment by msaraiva** [comment]
Fixed since v0.2.0.
