### ISSUE TITLE
Respect autocomplete+ completion keybinding

### ISSUE THREAD

**Issue by dvcrn** [msaraiva/atom-elixir#44]
atom-elixir binds `enter` in all `autocomplete-active` panes [here](https://github.com/msaraiva/atom-elixir/blob/master/keymaps/atom-elixir.cson#L34), this includes autocomplete+. 

[autocomplete plus is allowing rebinding of the confirm key](https://github.com/atom/autocomplete-plus#usage), however when atom-elixir is installed as well, `enter` will always confirm the completion and ignore autocomplete+ settings like shown in the keybinding helper here (autocomplete setting is on tab. Non elixir file): 

<img width="802" alt="screen shot 2016-08-21 at 12 01 40 pm" src="https://cloud.githubusercontent.com/assets/688326/17835170/827eba42-6799-11e6-8004-a439e9598022.png">

It would be great if atom-elixir can respect the settings made in autocomplete+, or use a more stricter selector for only elixir files and not editor wide

**Comment by clessg** [comment]
For anyone else with this issue, you can override this package's keybindings:

```cson
'atom-text-editor:not(mini).autocomplete-active':
  'enter': 'editor:newline'
```

**Comment by jhbrown** [comment]
I am experiencing this bug.   In Elixir files only, enter continues to autocomplete even when I have configured autocomplete+ to use only tab.   This is with Atom 1.24.0, atom-elixir 0.23, and autocomplete-plus 2.40.0, on OS X 10.13.3.
