### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by dax0** [msaraiva/atom-elixir#51]
I typically use a desktop so I'm not sure if this is an issue everywhere but on my laptop I noticed the `beam.smp` process that this plugin spawns ends up using 100% of my CPU.  Any idea?

**Comment by jmvl** [comment]
we are experiencing the same issue. 
`opt/appname/erts-8.2/bin/beam.smp -- -root /opt/appname`
is using 99% CPU

**Comment by msaraiva** [comment]
Please update to v0.2.2 and let me know if this still happens. Thanks!
