### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by jayjun** [msaraiva/atom-elixir#55]
The last commit was pushed six months ago.

With @msaraiva's blessing, I'll gladly maintain an official fork because it's been indispensible in my daily work.

**Comment by msaraiva** [comment]
@jayjun I'll split `atom-elixir` into two different projects as described [here](https://github.com/tonini/alchemist-server/issues/6#issuecomment-256243983). After that I intend to maintain only the project related to the server part. So, YES! I'd be more than glad if someone could fork and maintain the JS/CoffeScript part (the atom-elixir package itself).

**Comment by jayjun** [comment]
Super! I'll gladly maintain the CoffeeScript part. I'll let you take charge on how to proceed.

For now, I've forked this project as [atomic-elixir](https://github.com/jayjun/atomic-elixir).

**Comment by Sly777** [comment]
What's the difference between of atomic-elixir and atom-elixir now?

**Comment by jayjun** [comment]
@Sly777 It's a mirrored fork now. Earlier I fixed the depreciation issues and published atomic-elixir, but took it down when @msaraiva responded. Strangely, he hasn't push the update to apm.

If there's enough demand, I might go ahead and publish atomic-elixir.

**Comment by msaraiva** [comment]
I'll push a new version this evening containing @jayjun's fix and some other important stuff, including:
- Fix parser to work properly with Elixir 1.4.0.
- Fix code expansion to avoid high CPU usage (https://github.com/msaraiva/atom-elixir/issues/51).

After that I'll get back to work on a separated project containing only the Elixir parser/tools and then publish it as a different lib so that any editor can easily use it. I'll also try to make this new lib available as a `npm` package, so Atom and Code can use it straightaway without needing to copy, paste and change files manually.

**Comment by msaraiva** [comment]
@jayjun It's all on master. Can you or anybody else give it a try. Since this is the first version using the new lib (the Elixir part), I'd love to get some feedback before pushing the package to the official repo. If everything goes ok, I'll publish tomorrow. Thanks!

**Comment by jayjun** [comment]
@msaraiva I've been trialling master since you pushed and zero issues.

Also, great work on ElixirSense!

**Comment by msaraiva** [comment]
@jayjun That's great! I'll pull your latest changes and publish the package.

> ~~Spoke too soon. Jump to Definition does not work~~. Works perfectly when the project can compile

Yeah. Not only Jump To Definition, but also Go To Docs and Autocomplete only work for local project files if the those files have the respective `.beam` files available.

**Comment by msaraiva** [comment]
v0.2.2 has been published! Please let me know if the update process went well without any issues. Thanks!

**Comment by jayjun** [comment]
v0.2.2 works. Feel free to close this issue, we now know the package is still maintained. 😁
