### ISSUE TITLE
Not working on Linux

### ISSUE THREAD

**Issue by jc00ke** [msaraiva/atom-elixir#6]
I'm running `Atom 1.5.3` on `Ubuntu 15.10` and I've installed your package via `git`. The `apm install` went swimingly. When I tried to test out things, like autocomplete or go to docs nothing happens.

I'm new to Atom, so there's a good chance I don't have it set up correctly. I do have [language-elixir](https://atom.io/packages/language-elixir) installed.

`ctrl-space` is mapped to `autocomplete-plus:activate` at the moment.

I tried `alt-up` and though it's correctly bound it doesn't do anything.

Should I run [alchemist-server](https://github.com/tonini/alchemist-server) or start your extended server somehow?

This package looks amazing. Thanks for writing it!

**Comment by msaraiva** [comment]
Can you open the Dev Tools Panel and see if there's any message on the console?  Shortcut should be `ctrl-shift-i` on linux.

**Comment by jc00ke** [comment]
OK, super strange, but it works now. I had restarted it several times and... this time it works. I'll close for now and hope that it keeps working. The autocomplete is fast and accurate. Radness.
