### ISSUE TITLE
Support Remote Alchemist

### ISSUE THREAD

**Issue by rawkode** [msaraiva/atom-elixir#62]
Hi,

Can you add an option to supply my own alchemist-server URI?

I run everything in containers, and there's a whole load of permission issues when running your plugin.

I'd love to be able to specify my own alchemist host and port.

Thanks

**Comment by msaraiva** [comment]
@rawkode I've just pushed the initial version of a new TCPServer that will replace the one based on stdout/stderr. As soon as I have all features working, I'll remove the old one and then you'll be able to setup your own host/port. Right now, only the new "Signature/params Info" is using the new TCP server.

**Comment by rawkode** [comment]
Thanks, @msaraiva

Will you be separating ElixirSense and Atom plugin codebase so one could run ElixirSense in a Docker container?
