### ISSUE TITLE
Default docs stylesheet results in washed-out heading and code on light theme

### ISSUE THREAD

**Issue by lee-dohm** [msaraiva/atom-elixir#9]
Using built-in [one-light-ui theme](https://github.com/atom/one-light-ui). Screenshots taken from Logger documentation.

Header:

<img width="440" alt="logger-name-washed-out" src="https://cloud.githubusercontent.com/assets/1038121/13201118/6c858da8-d818-11e5-818e-8786dbc05f5a.png">

Code sample:

<img width="716" alt="screen shot 2016-02-20 at 9 24 20 pm" src="https://cloud.githubusercontent.com/assets/1038121/13201119/71ebae80-d818-11e5-9017-035b19201ff7.png">

**Comment by msaraiva** [comment]
Fixed! Using UI variables now.

I created another issue [(#11)](https://github.com/msaraiva/atom-elixir/issues/11) to review all other views using different themes.
 
@lee-dohm many thanks for taking time to test the package. I really appreciated.

**Comment by lee-dohm** [comment]
You're welcome! Love the ideas in the package even if I'm still a bit new to Elixir :grinning:

**Comment by msaraiva** [comment]
Yeah, I wish I had time to implement half of the ideas I have for this package. It would be really awesome ;)
